project_id = "tfrogqqqmgfgfybesglq"

[functions.llm-chat]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.send-friend-invitation-email]
verify_jwt = false

[functions.update-user-password]
verify_jwt = true
