project_id = "tjihfzitkehyaiznpjnc"

[functions.waitlist]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.send-friend-invitation-email]
verify_jwt = false

[functions.update-user-password]
verify_jwt = true

[functions.send-secret-santa-notification]
verify_jwt = false

[functions.get-admin-data]
verify_jwt = false

[functions.get-email-logs]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = false

[functions.email-templates]
verify_jwt = false
